### ISSUE TITLE
libotr 4.1.x support

### ISSUE THREAD

**Issue by ysangkok** [cryptodotis/irssi-otr#50]
The readme says that irssi-otr needs libotr 4.0.x. This is not the latest version and it is an inconvenience.

**Comment by andreasstieger** [comment]
Works fine with libotr 4.1.0, there is no special support required. Do you have a specific issue with this version?

**Comment by ysangkok** [comment]
I just tried building with the new version, and it seems to work. But I'm uncomfortable disobeying the instructions.

**Comment by dgoulet** [comment]
I just updated the README that contained some old info.

Thanks for the report!

**Comment by andreasstieger** [comment]
I think the more strict 4.1.x in 4ad3b7b6c85be0154ab3694fe9831796db20c4fe is wrong or at least incomplete. libotr >= 4.0.0 is sufficient and matches configure.ac?

**Comment by dgoulet** [comment]
On 12 Jan (11:41:06), Andreas Stieger wrote:
> I think the more strict 4.1.x in 4ad3b7b6c85be0154ab3694fe9831796db20c4fe is wrong or at least incomplete. libotr >= 4.0.0 is sufficient and matches configure.ac?

4.1.0 has a critical fix for irssi-otr which before distros had to pull
it manually in their package.

So, I would really advocate for 4.1.x here because of that.

**Comment by andreasstieger** [comment]
As a distribution package maintainer I am aware of that, but would recommend the above for completeness.
