### ISSUE TITLE
./configure --prefix not working

### ISSUE THREAD

**Issue by dt1973** [cryptodotis/irssi-otr#53]
Expanding on https://github.com/cryptodotis/irssi-otr/issues/52 -- does anybody know why it's still trying to install parts into `/usr/` despite specifying `--prefix=$HOME --with-irssi-module-dir=$HOME/.irssi/modules --docdir=$HOME --infodir=$HOME --mandir=$HOME`?

```
make[2]: Nothing to be done for `install-exec-am'.
/bin/mkdir -p '/usr/share/irssi/help'
/usr/bin/install -c -m 644 otr '/usr/share/irssi/help'
/usr/bin/install: cannot create regular file `/usr/share/irssi/help/otr': Permission denied
```

**Comment by dt1973** [comment]
Note that ones `--prefix` dir must also be repeated in `IRSSI_DIST` in `irssi-otr/src/Makefile.am` for `./configure` to work. Ideally the user shouldn't have to do this.

**Comment by Rhialto** [comment]
In pkgsrc, irssi is forced to install into its idea of $(prefix), typically /usr/pkg. For that purpose I have the following patches to match that:
```
$NetBSD$

Our irssi installs in $(prefix).

--- help/Makefile.am.orig       2015-07-19 16:12:13.000000000 +0000
+++ help/Makefile.am
@@ -1,6 +1,6 @@
 # The day Irssi will be able to check in $(prefix), this will change. Until
 # then, it's hardcoded.
-helpdir = /usr/share/irssi/help
+helpdir = $(prefix)/share/irssi/help
 help_DATA = otr
 
 EXTRA_DIST = otr
```
```
$NetBSD$

Our irssi installs in $(prefix).

--- src/Makefile.am.orig        2015-07-19 16:12:13.000000000 +0000
+++ src/Makefile.am
@@ -1,6 +1,6 @@
 AM_CFLAGS = $(LIBOTR_CFLAGS) $(LIBGCRYPT_CFLAGS) $(PACKAGE_FLAGS)
 
-IRSSI_DIST=/usr/include/irssi
+IRSSI_DIST=$(prefix)/include/irssi
 IRSSI_INCLUDE = -I$(IRSSI_DIST) \
                                -I$(IRSSI_DIST)/src \
                                -I$(IRSSI_DIST)/src/fe-common/core \
```

**Comment by anarcat** [comment]
this also affects multi-arch debian installs: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=817172

patch incoming.
