### ISSUE TITLE
Missing release tag for 1.0.1

### ISSUE THREAD

**Issue by anthraxx** [cryptodotis/irssi-otr#54]
Hello,

according to the commit f0a4d998643df6a50ece578ffa711bdd49a406af it looks like 1.0.1 is already stated as "released" back in January. If thats the case, can you please also push a git tag for 1.0.1 so github is providing a tarball and also upstream release tracking works properly?

cheers,
anthraxx

**Comment by Rhialto** [comment]
Seconded...

**Comment by tg-x** [comment]
+1

**Comment by n0la** [comment]
The release has actually received an actual release tarball that can be downloaded here:
https://www.otr.im/dist/irssi-otr/

You should use this instead of the github tarball.

**Comment by tg-x** [comment]
Still, it's good to tag the source as well.

**Comment by anthraxx** [comment]
yes, I will pull the sources now from the tarball on the webserver that also offers a signature. However I would still like to have git tags that reflect the releases. Its also much cleaner to track new releases :yum:

**Comment by anarcat** [comment]
i can confirm that the missing tag is f0a4d99, after checking https://www.otr.im/dist/irssi-otr/irssi-otr-1.0.1.tar.bz2.asc (including verifying the signature).

i have pushed the relevant tag in my fork in https://github.com/anarcat/irssi-otr - therefore, this should fix the problem for otr maintainers:

```
git remote add anarcat git@github.com:anarcat/irssi-otr.git
git remote update
git push
```

**Comment by dgoulet** [comment]
I just pushed the missing tag that is 1.0.1 ... epic fail on my part on 1) noticing this issue and 2) acting so late... Sorry everyone :S
