### ISSUE TITLE
Use ECDSA keys instead of DSA keys

### ISSUE THREAD

**Issue by cmouse** [cryptodotis/irssi-otr#57]
Would it be possible to consider to use ECDSA keys instead of DSA keys in OTR?

**Comment by cfcs** [comment]
Yes. The spec allows custom signing algorithms. Do you have a specific use case for this?

**Comment by cmouse** [comment]
You use dsa keys at the moment. Was thinking that it would be nice to be able to migrate to ecdsa keys which are faster to generate and use. No specific use case in mind.

**Comment by cfcs** [comment]
It would not be compatible with any other OTR implementation, and the actual link encryption would still depend on the 1536-bit Diffie-Hellman key exchange (NIST recommendation from 2010 says that anything under 2048-bit should be considered insecure).

If you don't mind not being backwards compatible with OTR, there are other options.

Among others:
- http://conversations.im/omemo/
- Ricochet
- Tox

**Comment by DrWhax** [comment]
This is not the right repo for that, in addition, this should go into a specification. Closing ticket. Feel free to raise the issue on the otr-dev mailinglist.

**Comment by cmouse** [comment]
Thanks. I'll consider it.
