### ISSUE TITLE
Syntax Error, line 12412

### ISSUE THREAD

**Issue by c650** [cryptodotis/irssi-otr#66]
Hello,

I'm trying to install this software and I'm following the steps:

Running `./configure --prefix="/usr"` goes smoothly until it yields this error:
```
./configure: line 12412: syntax error near unexpected token `1:1.2.0,as_fn_error'
./configure: line 12412: `AM_PATH_LIBGCRYPT(1:1.2.0,,as_fn_error $? "libgcrypt 1.2.0 or newer is required." "$LINENO" 5)'
```

Considering that I don't know much about bash scripting, I'm lost at this point and I cannot install this software.

I'm running Ubuntu 16.04 x64.

**Comment by dgoulet** [comment]
Do you have all the requirements installed? See README.

**Comment by c650** [comment]
@dgoulet yes I have `libgcrypt20-dev` installed and I even ran `sudo apt install --reinstall libgcrypt20-dev`

**Comment by dgoulet** [comment]
Try `apt install pkg-config` ?

**Comment by c650** [comment]
@dgoulet that package is already installed at this point. I think I installed it earlier in response to another error.

**Comment by dgoulet** [comment]
I'm quite confused... I just tried on a 16.04 x64 and it works out of the box with the requirements....

If you can run `autogen.sh` properly and you have pkg-config, it suppose to be enough. Maybe Googling a bit the error can give you some advise because it seems more of autoconf issue.

**Comment by Rhialto** [comment]
To me it looks like the line

```
AM_PATH_LIBGCRYPT(1:1.2.0,,AC_MSG_ERROR(libgcrypt 1.2.0 or newer is required.))
```

from the file `configure.ac` hasn't been processed into shell script.

**Comment by c650** [comment]
Now __I'm__ quite confused because I got a new copy of the repo and it worked!

Fishy.
